// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEunCw5hJg5Tr7UXcr5EKLppkWkq1qVOE',
    appId: '1:95560342958:web:390f99818682cda8b7fc3f',
    messagingSenderId: '95560342958',
    projectId: 'cradd-2b709',
    authDomain: 'cradd-2b709.firebaseapp.com',
    storageBucket: 'cradd-2b709.firebasestorage.app',
    measurementId: 'G-GNDLG9NVMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv-gExGvVoRLqc-3ZY5LL4gba9bGKcJyU',
    appId: '1:95560342958:android:01f61dc9d70f5ed5b7fc3f',
    messagingSenderId: '95560342958',
    projectId: 'cradd-2b709',
    storageBucket: 'cradd-2b709.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsOqcHptzg8ORV1qxEu8b2RBPrB151PJQ',
    appId: '1:95560342958:ios:005db7371b3ecde4b7fc3f',
    messagingSenderId: '95560342958',
    projectId: 'cradd-2b709',
    storageBucket: 'cradd-2b709.firebasestorage.app',
    iosBundleId: 'com.example.cradiusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsOqcHptzg8ORV1qxEu8b2RBPrB151PJQ',
    appId: '1:95560342958:ios:005db7371b3ecde4b7fc3f',
    messagingSenderId: '95560342958',
    projectId: 'cradd-2b709',
    storageBucket: 'cradd-2b709.firebasestorage.app',
    iosBundleId: 'com.example.cradiusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEunCw5hJg5Tr7UXcr5EKLppkWkq1qVOE',
    appId: '1:95560342958:web:dd8740c471ba74fbb7fc3f',
    messagingSenderId: '95560342958',
    projectId: 'cradd-2b709',
    authDomain: 'cradd-2b709.firebaseapp.com',
    storageBucket: 'cradd-2b709.firebasestorage.app',
    measurementId: 'G-0R6Y86L3D0',
  );

}